/* 
==============================================================================
DDL Scripts: Create Bronze Tables
==============================================================================
Script Purpose:
  This script creats tables in the 'bronze' schema, dropping existing tables 
  if they already exist.
  Run this script to re_define the DDL structure of 'bronze Tables
==============================================================================
*/
  

